// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRCrwNHkXeJwruIWA3ohOzY2yMAMfrzY',
    appId: '1:10531242268:web:deef939e57ba32221ebad9',
    messagingSenderId: '10531242268',
    projectId: 'polls-92f94',
    authDomain: 'polls-92f94.firebaseapp.com',
    databaseURL: 'https://polls-92f94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'polls-92f94.appspot.com',
    measurementId: 'G-VKPVJFFN1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7-SDs6e8vbDI-GGyWkvNJ6BdO8mOBG4',
    appId: '1:10531242268:android:46762bb31883370f1ebad9',
    messagingSenderId: '10531242268',
    projectId: 'polls-92f94',
    databaseURL: 'https://polls-92f94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'polls-92f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFARDoFMIILA8lUBZZR0YEy2Fh1PLPA7I',
    appId: '1:10531242268:ios:9ec69044d724c4181ebad9',
    messagingSenderId: '10531242268',
    projectId: 'polls-92f94',
    databaseURL: 'https://polls-92f94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'polls-92f94.appspot.com',
    iosClientId: '10531242268-7b58g6nktumnt57emiia1qe2vn2f3gn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPolls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFARDoFMIILA8lUBZZR0YEy2Fh1PLPA7I',
    appId: '1:10531242268:ios:9ec69044d724c4181ebad9',
    messagingSenderId: '10531242268',
    projectId: 'polls-92f94',
    databaseURL: 'https://polls-92f94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'polls-92f94.appspot.com',
    iosClientId: '10531242268-7b58g6nktumnt57emiia1qe2vn2f3gn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPolls',
  );
}
